---
resources:
- name: onboarding-concourse
  type: git
  source:
    uri: git@github.com:ndhanushkodi/onboarding-concourse.git
    branch: master
    private_key: ((private-repo-key))
- name: hello-docker
  type: docker-image
  source:
    repository: consul

jobs:
  - name: jobby-job
    plan:
    - get: onboarding-concourse
      trigger: true
    - get: hello-docker
    - task: hello
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args: [hello world]
    - task: run-container
      file: onboarding-concourse/ci/run-container/task.yml
